return {
    python = "pyright",
    lua = "lua_ls",
    rust = "rust_analyzer",
    go = "gopls",
    c = "clangd",
    cpp = "clangd",
    java = "jdtls",
    typescript = "tsserver",
    javascript = "tsserver",
    typescriptreact = "tsserver",
    javascriptreact = "tsserver",
    html = "html",
    css = "tailwindcss",
    scss = "tailwindcss",
    astro = "astro",
    zig = "zls",
    dockerfile = "dockerls",
    sh = "bashls",
    zsh = "bashls",
    cmake = "cmake",
    ocaml = "ocamllsp",
    dune = "ocamllsp",
}
